spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_store?serverTimezone=UTC
    username: root
    password: 263661
server:
  port: 8082

logging:
  level:
    com.sys.appstore: debug

project:
  filepath: D:\tmp\image\